# P9_MicroStream Configuration
# Institutional-Grade Market Data Infrastructure - FOCUSED ON SOL ONLY

server:
  port: 8080
  host: "0.0.0.0"
  metrics_port: 9090
  health_port: 8081

logging:
  level: "info"
  format: "json"
  output: "logs/p9_microstream.log"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  pool_size: 10
  max_retries: 3
  dial_timeout: "5s"

# SERVICE GROUPS - Organized for better management
service_groups:
  # Group 1: Core Infrastructure (Always Running)
  core:
    enabled: true
    services:
      - websocket_workers
      - redis_publisher
      - event_parser
      - health_monitor
    
  # Group 2: Real-time Analytics (High Priority)
  analytics:
    enabled: true
    services:
      - cvd_calculator
      - whale_tracker
      - momentum_detector
      - volatility_monitor
      - spoofing_detector
      - ohlcv_candle_generator
      - order_flow_analyzer
      - orderbook_analyzer
    
  # Group 3: Market Structure Analysis (Medium Priority)  
  market_structure:
    enabled: true
    services:
      - book_imbalance_detector
      - orderbook_heatmap
      - liquidation_monitor
      - mean_reversion_tracker
      - iceberg_detector
    
  # Group 4: Advanced Analytics (Lower Priority)
  advanced:
    enabled: true
    services:
      - velocity_analyzer
      - liquidity_vacuum_analyzer
      - vpin_analyzer
      - delta_tape_analyzer
      - regime_classifier

# Exchange Configuration - FOCUSED ON SOL ONLY
exchanges:
  - name: "binance"
    enabled: true
    websocket_url: "wss://stream.binance.com:9443/ws/"
    symbols: ["solusdt"]  # SOL ONLY
    services:
      orderbook: true
      trade: true
      liquidation: false
      cvd: true
      whale_tracker: true
      book_imbalance: true
      spoofing: true
      momentum: true
      iceberg: true
      mean_reversion: true
      volatility: true
      ohlcv_candles: true
      order_flow: true
      orderbook_analysis: true
      velocity_analyzer: true
      liquidity_vacuum_analyzer: true
      vpin_analyzer: true
      delta_tape_analyzer: true
      orderbook_heatmap: true
      liquidation_monitor: false
      htf_bias_analyzer: true
      microstructure_anomaly: true
    heartbeat_interval: "30s"
    reconnect_backoff: "5s"
    max_reconnect_attempts: 10

  - name: "bybit"
    enabled: true
    symbols: ["solusdt"]  # SOL ONLY
    websocket_url: "wss://stream.bybit.com/v5/public/linear"
    services:
      orderbook: true
      trade: true
      liquidation: true
      cvd: true
      whale_tracker: true
      book_imbalance: true
      spoofing: true
      momentum: true
      iceberg: true
      mean_reversion: true
      volatility: true
      ohlcv_candles: true
      order_flow: true
      orderbook_analysis: true
      velocity_analyzer: true
      liquidity_vacuum_analyzer: true
      vpin_analyzer: true
      delta_tape_analyzer: true
      orderbook_heatmap: true
      liquidation_monitor: true
      htf_bias_analyzer: true
      microstructure_anomaly: true
    heartbeat_interval: "20s"
    reconnect_backoff: "3s"
    max_reconnect_attempts: 15

  - name: "okx"
    enabled: true
    websocket_url: "wss://ws.okx.com:8443/ws/v5/public"
    symbols: ["sol-usdt"]  # SOL ONLY (OKX format)
    services:
      orderbook: true
      trade: true
      liquidation: true
      cvd: true
      whale_tracker: true
      book_imbalance: true
      spoofing: false
      momentum: true
      iceberg: false
      mean_reversion: true
      volatility: true
      ohlcv_candles: true
      order_flow: true
      orderbook_analysis: true
      velocity_analyzer: true
      liquidity_vacuum_analyzer: true
      vpin_analyzer: true
      delta_tape_analyzer: true
      orderbook_heatmap: true
      liquidation_monitor: true
      htf_bias_analyzer: true
      microstructure_anomaly: false
    heartbeat_interval: "30s"
    reconnect_backoff: "5s"
    max_reconnect_attempts: 12

# Symbol Configuration - SOL ONLY
symbols:
  solusdt:
    enabled: true
    whale_threshold: 200  # $200 threshold for SOL
    book_levels: 1000  # DEEP ORDER BOOK - 1000 levels for institutional analysis
    cvd_window: "30s"
    volatility_windows: ["30s", "1m", "5m"]
    candle_timeframes: ["1s", "5s", "15s", "30s", "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "12h", "1d"]
    order_flow_analysis: true
    orderbook_depth_analysis: true
    wall_detection_threshold: 1000.0  # SOL volume threshold for wall detection

  sol-usdt:  # OKX format
    enabled: true
    whale_threshold: 200  # $200 threshold for SOL on OKX
    book_levels: 1000  # DEEP ORDER BOOK - 1000 levels for institutional analysis
    cvd_window: "30s"
    volatility_windows: ["30s", "1m", "5m"]
    candle_timeframes: ["1s", "5s", "15s", "30s", "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "12h", "1d"]
    order_flow_analysis: true
    orderbook_depth_analysis: true
    wall_detection_threshold: 1000.0  # SOL volume threshold for wall detection

# Analytics Configuration
analytics:
  cvd_calculator:
    enabled: true
    timeframes: ["1m", "5m", "15m"]
    
  whale_tracker:
    enabled: true
    thresholds:
      solusdt: 200.0    # SOL threshold
      sol-usdt: 200.0   # OKX format
      
  momentum_detector:
    enabled: true
    price_change_threshold: 0.2  # Much lower threshold - 0.2% (was 0.5%)
    volume_threshold: 1.2        # Lower volume requirement (was 1.5)
    time_window: 15              # Shorter window for faster detection (was 30)
    
  volatility_monitor:
    enabled: true
    timeframes: ["1m", "5m", "15m"]
    spike_threshold: 1.2         # Much lower threshold (was 2.0)
    
  spoofing_detector:
    enabled: true
    min_order_size: 50.0         # Lower minimum order size (was 100.0)
    cancellation_threshold: 0.6  # Lower threshold - more sensitive (was 0.8)
    phantom_liquidity_threshold: 0.5  # Lower threshold - more sensitive (was 0.7)

  # FUNDING RATE AGGREGATOR - NEW IMPLEMENTATION
  funding_rate_aggregator:
    enabled: true
    poll_interval: "30s"  # REST polling interval for funding rates

  # MARK PRICE POLLER - NEW IMPLEMENTATION
  mark_price_poller:
    enabled: true
    poll_interval: "10s"  # REST polling interval for mark prices (faster than funding rates)

  # OPEN INTEREST POLLER - NEW IMPLEMENTATION
  open_interest_poller:
    enabled: true
    poll_interval: "15s"  # REST polling interval for open interest data

  # DEPTH GAP WATCHER - DATA INTEGRITY MONITORING
  depth_gap_watcher:
    enabled: true
    max_gap_size: 10      # Trigger snapshot request if gap > 10
    gap_timeout: "30s"    # Trigger if no updates for 30s

  # BOOK TICKER AGGREGATOR - ITEM 13: ORDER-BOOK IMBALANCE/LADDER EVENTS
  book_ticker_aggregator:
    enabled: true
    publish_channel: "book_ticker"
    imbalance_tracking: true

  # PERIODIC SNAPSHOTS - ITEM 3: REGULAR BOOK SNAPSHOTS  
  periodic_snapshots:
    enabled: true
    interval: "1s"        # Snapshot every 1 second for lossless recovery
    storage_duration: "24h" # Keep snapshots for 24 hours

  # INSURANCE FUND MONITOR - ITEM 12: INSURANCE FUND BALANCE
  insurance_fund_monitor:
    enabled: true
    poll_interval: "5m"   # Poll every 5 minutes
    exchanges: ["binance", "bybit"]  # OKX doesn't expose insurance fund
    stress_thresholds:
      critical: -10.0     # >10% decrease
      high: -5.0         # 5-10% decrease  
      medium: -1.0       # 1-5% decrease

  # REDIS PUBLISH CONFIRMER - ITEM 26: REDIS PUBLISH-CONFIRM/RETRY
  redis_publish_confirmer:
    enabled: true
    max_retries: 3
    retry_delay: "500ms"
    confirm_timeout: "5s"
    priority_queues: ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

  # MULTI-TIMEFRAME OHLCV CANDLE GENERATOR
  ohlcv_candle_generator:
    enabled: true
    timeframes: ["1s", "5s", "15s", "30s", "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "12h", "1d"]
    publish_channels:
      format: "candles:{SYMBOL}:{TIMEFRAME}"  # e.g., candles:SOLUSDT:1m
    vwap_calculation: true
    taker_volume_tracking: true
    
  # ENHANCED ORDER FLOW ANALYZER
  order_flow_analyzer:
    enabled: true
    whale_thresholds:
      solusdt: 200.0   # $200 for SOL trades
      sol-usdt: 200.0  # $200 for SOL on OKX
    publish_channels:
      format: "orderflow:{SYMBOL}"  # e.g., orderflow:SOLUSDT
    price_impact_analysis: true
    flow_type_classification: true
    micro_trend_detection: true
    book_pressure_analysis: true
    
  # COMPREHENSIVE ORDERBOOK ANALYZER
  orderbook_analyzer:
    enabled: true
    wall_detection_thresholds:
      solusdt: 1000.0   # 1000 SOL minimum for wall
      sol-usdt: 1000.0  # 1000 SOL minimum for wall on OKX
    publish_channels:
      format: "orderbook:{SYMBOL}"  # e.g., orderbook:SOLUSDT
    depth_analysis_levels: [5, 10, 20, 50]  # Analyze liquidity at these depths
    wall_significance_levels: ["MINOR", "MODERATE", "MAJOR", "MASSIVE"]
    imbalance_tracking: true
    liquidity_profiling: true

# DETECTION ENGINES
detectors:
  book_imbalance:
    enabled: true
    imbalance_threshold: 0.7
    
  orderbook_heatmap:
    enabled: true
    depth_levels: 20
    
  liquidation_monitor:
    enabled: true
    cluster_threshold: 10000.0
    
  mean_reversion:
    enabled: true
    z_score_threshold: 2.0
    
  iceberg_detector:
    enabled: true
    fragment_threshold: 0.1

# ADVANCED ANALYTICS
advanced_analytics:
  velocity_analyzer:
    enabled: true
    timeframes: ["10s", "30s", "1m", "2m", "5m"]
    velocity_threshold: 0.1      # Lower threshold for velocity detection
    
  liquidity_vacuum_analyzer:
    enabled: true
    vacuum_threshold: 0.2        # Lower threshold (was 0.3)
    
  vpin_analyzer:
    enabled: true
    bucket_size: 50              # Smaller buckets for faster detection (was 100)
    num_buckets: 50
    toxicity_threshold: 0.6      # Lower threshold for toxicity alerts
    
  delta_tape_analyzer:
    enabled: true
    flow_threshold: 500.0        # Lower threshold (was 1000.0)
    
  regime_classifier:
    enabled: true
    volatility_threshold: 10.0   # Lower threshold (was 15.0)

# MONITORING
monitoring:
  health_check_interval: 30
  metrics_enabled: true
  prometheus_port: 9090

# Performance Configuration
performance:
  buffer_size: 1000
  batch_size: 100
  flush_interval: "1s"
  max_memory_mb: 512

# Worker Configuration - Optimized for SOL only
workers:
  websocket_workers: 3  # One per exchange (Binance, Bybit, OKX)
  analytics_workers: 12  # All analytics services
  detection_workers: 9   # All detection services
  auxiliary_workers: 6   # Auxiliary services
  total_workers: 30

# Security Configuration
security:
  rate_limiting:
    enabled: true
    requests_per_second: 1000
    burst: 2000
  
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST"]

# Deep Order Book Configuration - INSTITUTIONAL GRADE - SOL OPTIMIZED
deep_orderbook:
  enabled: true
  max_levels: 1000  # Maximum levels per side
  update_frequency: "100ms"  # Balance between speed and data quality
  memory_optimization: true
  compression: true
  analytics:
    liquidity_profiling: true
    iceberg_detection: true
    spoofing_analysis: true
    market_impact_calculation: true 