version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: p9_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  p9_microstream:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: p9_microstream
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../configs:/app/configs
      - ../logs:/app/logs
    restart: unless-stopped

volumes:
  redis_data:
